### ISSUE TITLE
[Edit required] Issue during Heroku building

### ISSUE THREAD

**Issue by angsm** [twilio/mobile-quickstart#11]
Hi Twilio,

I have encountered an error trying to deploy directly to Heroku using the embedded button in the documentation. The error is as below. It seems that Heroku already has "six" installed, and by removing the "six" from requirements.txt, the deployment works.

         Found existing installation: six 1.10.0
           Uninstalling six-1.10.0:
             Successfully uninstalled six-1.10.0
         Rolling back uninstall of six
       Exception:
       Traceback (most recent call last):
         File "/app/.heroku/python/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main
           status = self.run(options, args)
         File "/app/.heroku/python/lib/python2.7/site-packages/pip/commands/install.py", line 342, in run
           prefix=options.prefix_path,
         File "/app/.heroku/python/lib/python2.7/site-packages/pip/req/req_set.py", line 784, in install
           **kwargs
         File "/app/.heroku/python/lib/python2.7/site-packages/pip/req/req_install.py", line 851, in install
           self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
         File "/app/.heroku/python/lib/python2.7/site-packages/pip/req/req_install.py", line 1064, in move_wheel_files
           isolated=self.isolated,
         File "/app/.heroku/python/lib/python2.7/site-packages/pip/wheel.py", line 247, in move_wheel_files
           prefix=prefix,
         File "/app/.heroku/python/lib/python2.7/site-packages/pip/locations.py", line 140, in distutils_scheme
           d = Distribution(dist_args)
         File "/app/.heroku/python/lib/python2.7/site-packages/setuptools/dist.py", line 321, in __init__
           _Distribution.__init__(self, attrs)
         File "/app/.heroku/python/lib/python2.7/distutils/dist.py", line 287, in __init__
           self.finalize_options()
         File "/app/.heroku/python/lib/python2.7/site-packages/setuptools/dist.py", line 389, in finalize_options
           ep.require(installer=self.fetch_build_egg)
         File "/app/.heroku/python/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2324, in require
           items = working_set.resolve(reqs, env, installer, extras=self.extras)
         File "/app/.heroku/python/lib/python2.7/site-packages/pkg_resources/__init__.py", line 862, in resolve
           new_requirements = dist.requires(req.extras)[::-1]
         File "/app/.heroku/python/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2568, in requires
           dm = self._dep_map
         File "/app/.heroku/python/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2815, in _dep_map
           self.__dep_map = self._compute_dependencies()
         File "/app/.heroku/python/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2824, in _compute_dependencies
           for req in self._parsed_pkg_info.get_all('Requires-Dist') or []:
         File "/app/.heroku/python/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2806, in _parsed_pkg_info
           metadata = self.get_metadata(self.PKG_INFO)
         File "/app/.heroku/python/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1468, in get_metadata
           value = self._get(self._fn(self.egg_info, name))
         File "/app/.heroku/python/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1577, in _get
           with open(path, 'rb') as stream:
       IOError: [Errno 2] No such file or directory: '/tmp/build_eb68d974d1944be15b58d5fdf8a811bd/twilio-mobile-quickstart-10294f7/.heroku/python/lib/python2.7/site-packages/six-1.10.0.dist-info/METADATA'
 !     Push rejected, failed to compile Python app.
 !     Push failed

**Comment by bchen-twilio** [comment]
Hi @angsm 

Sorry for the inconvenience when installing the library dependencies.
For now could you modify the `requirements.txt` and replace the line for `six` like this?
```
six==1.*
```

The Twilio python helper library needs `six` for interoperability between python 2 & 3, but most of the cloud hosting services already have the latest or newer versions installed with their virtual instances. We will update our sample code as well.

Please let us know if this helps.
Thanks.

-bobie
Twilio SDK Engineering

**Comment by pons1991** [comment]
It works great
