### ISSUE TITLE
Unicode error in client -> PSTN call.

### ISSUE THREAD

**Issue by yehe01** [twilio/mobile-quickstart#8]
When executing the `str(resp)` line:

```
    if not (from_value and to):
        resp.say("Invalid request")
        return str(resp)
    from_client = from_value.startswith('client')
    caller_id = os.environ.get("CALLER_ID", CALLER_ID)
    if not from_client:
        # PSTN -> client
        resp.dial(callerId=from_value).client(CLIENT)
    elif to.startswith("client:"):
        # client -> client
        resp.dial(callerId=from_value).client(to[7:])
    else:
        # client -> PSTN
        resp.dial(to, callerId=caller_id)
        print "client -> PSTN"

    print str(resp)
    return str(resp)
```
it threw the following error:

> at=info method=POST path="/call" host=twilio-center2.herokuapp.com request_id=1fd5d66b-2261-40b5-b5ff-d0fa2e2c09cf fwd="54.87.230.246" dyno=web.1 connect=0ms service=17ms status=500 bytes=12483
2016-05-18T04:23:07.871549+00:00 app[web.1]: 10.141.10.134 - - [18/May/2016 04:23:07] "POST /call HTTP/1.1" 500 -
2016-05-18T04:23:07.872037+00:00 app[web.1]: Traceback (most recent call last):
2016-05-18T04:23:07.872056+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
2016-05-18T04:23:07.872057+00:00 app[web.1]:     return self.wsgi_app(environ, start_response)
2016-05-18T04:23:07.872058+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
2016-05-18T04:23:07.872059+00:00 app[web.1]:     response = self.make_response(self.handle_exception(e))
2016-05-18T04:23:07.872059+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
2016-05-18T04:23:07.872060+00:00 app[web.1]:     reraise(exc_type, exc_value, tb)
2016-05-18T04:23:07.872061+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
2016-05-18T04:23:07.872061+00:00 app[web.1]:     response = self.full_dispatch_request()
2016-05-18T04:23:07.872062+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
2016-05-18T04:23:07.872063+00:00 app[web.1]:     rv = self.handle_user_exception(e)
2016-05-18T04:23:07.872063+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
2016-05-18T04:23:07.872064+00:00 app[web.1]:     reraise(exc_type, exc_value, tb)
2016-05-18T04:23:07.872065+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
2016-05-18T04:23:07.872065+00:00 app[web.1]:     rv = self.dispatch_request()
2016-05-18T04:23:07.872066+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
2016-05-18T04:23:07.872067+00:00 app[web.1]:     return self.view_functions[rule.endpoint](**req.view_args)
2016-05-18T04:23:07.872067+00:00 app[web.1]:   File "/app/server.py", line 62, in call
2016-05-18T04:23:07.872068+00:00 app[web.1]:     return str(resp)
2016-05-18T04:23:07.872069+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/twilio/twiml.py", line 38, in __str__
2016-05-18T04:23:07.872070+00:00 app[web.1]:     return self.toxml()
2016-05-18T04:23:07.872070+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/twilio/twiml.py", line 53, in toxml
2016-05-18T04:23:07.872071+00:00 app[web.1]:     xml = ET.tostring(self.xml()).decode('utf-8')
2016-05-18T04:23:07.872072+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/xml/etree/ElementTree.py", line 1126, in tostring
2016-05-18T04:23:07.872072+00:00 app[web.1]:     ElementTree(element).write(file, encoding, method=method)
2016-05-18T04:23:07.872073+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/xml/etree/ElementTree.py", line 820, in write
2016-05-18T04:23:07.872073+00:00 app[web.1]:     serialize(write, self._root, encoding, qnames, namespaces)
2016-05-18T04:23:07.872074+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/xml/etree/ElementTree.py", line 939, in _serialize_xml
2016-05-18T04:23:07.872074+00:00 app[web.1]:     _serialize_xml(write, e, encoding, qnames, None)
2016-05-18T04:23:07.872075+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/xml/etree/ElementTree.py", line 932, in _serialize_xml
2016-05-18T04:23:07.872076+00:00 app[web.1]:     v = _escape_attrib(v, encoding)
2016-05-18T04:23:07.872077+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/xml/etree/ElementTree.py", line 1090, in _escape_attrib
2016-05-18T04:23:07.872077+00:00 app[web.1]:     return text.encode(encoding, "xmlcharrefreplace")
2016-05-18T04:23:07.872078+00:00 app[web.1]: UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 12: ordinal not in range(128)

**Comment by yehe01** [comment]
It worked before.

**Comment by yehe01** [comment]
BTW client -> clent works fine. Which is this switch: `elif to.startswith("client:"):`

**Comment by yehe01** [comment]
Any plan on fixing this?

**Comment by vassjozsef** [comment]
Please see https://www.twilio.com/docs/api/client/capability-tokens: The client identifier currently may only contain alpha-numeric and underscore characters.

Which resource are you using {{/token}} or {{/cal}}? What is the client name are you using?

**Comment by yehe01** [comment]
What do you mean by resource?
I didn't change the source code except configuring the env vars on Heroku and adding some printing statements.
You can get token from my deplyed app https://twilio-center.herokuapp.com/token
The client names are just simple names like tom, jenny, etc.

It worked before from client to client.

**Comment by yehe01** [comment]
I think I've figured it out. I have two phone numbers. One for Twilio account registration, which was added as a **verified caller id**. The other one is a phone number I got from Twilio.
The issue happens only when using the later unverified one.

Thanks for help.
